version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17  # Pastikan image ini ada dan tersedia
    working_directory: ~/repo  # Direktori kerja untuk job

jobs:
  build:
    executor: java-executor  # Executor yang digunakan untuk job ini
    steps:
      - checkout  # Mengambil kode sumber dari repositori
      - run:
          name: Install Gradle 8.6  # Langkah untuk menginstal Gradle
          command: |
            wget https://services.gradle.org/distributions/gradle-8.6-bin.zip
            unzip gradle-8.6-bin.zip
            sudo mv gradle-8.6 /opt/gradle
            sudo ln -s /opt/gradle/bin/gradle /usr/bin/gradle
      - run:
          name: Gradle Build  # Langkah untuk membangun proyek
          command: gradle build  # Perintah untuk membangun proyek
      - run:
          name: Gradle Test  # Langkah untuk menjalankan tes
          command: gradle test  # Perintah untuk menjalankan tes

workflows:
  version: 2
  build_and_test:
    jobs:
      - build  # Menjalankan job build dalam workflow ini
