version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:latest
    steps:
      - checkout
      - run:
          name: Update Package List and Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-17-jdk
      - run:
          name: Make Gradlew Executable
          command: chmod +x ./gradlew
      - run:
          name: Create local.properties
          command: echo "sdk.dir=$ANDROID_HOME" > local.properties
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Archive APK
          command: |
            mkdir -p $HOME/artifacts
            cp app/build/outputs/apk/release/app-release.apk $HOME/artifacts/
      - store_artifacts:
          path: $HOME/artifacts
          destination: artifacts

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
