version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Atau image Docker lain yang sesuai
    steps:
      - checkout
      - run:
          name: Update Package List and Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-17-jdk
      - run:
          name: Set JAVA_HOME
          command: |
            echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Make Gradlew Executable
          command: chmod +x ./gradlew
      - run:
          name: Build Project
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
