version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30-ndk-jdk17
    steps:
      - checkout
      - run:
          name: Verify Java Version
          command: |
            java -version
            javac -version
      - run:
          name: Chmod Gradlew Permissions
          command: chmod +x ./gradlew
      - run:
          name: Build Project
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
