version: 2.1

# Define a job to build the Android project.
jobs:
  build:
    docker:
      - image: cimg/android:2024.08.01 # Using an Android image with Gradle pre-installed

    steps:
      - checkout
      - run:
          name: Set Up Gradle Permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Gradle Dependencies
          command: ./gradlew dependencies --no-daemon
      - run:
          name: Build APK
          command: ./gradlew assembleDebug --no-daemon
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest --no-daemon
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apk-debug
      - store_artifacts:
          path: core/build/outputs/apk/debug/
          destination: core-apk-debug
      - store_artifacts:
          path: favorite/build/outputs/apk/debug/
          destination: favorite-apk-debug

  lint:
    docker:
      - image: cimg/android:2024.08.01

    steps:
      - checkout
      - run:
          name: Set Up Gradle Permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Run Lint Checks
          command: ./gradlew lintDebug --no-daemon
      - store_artifacts:
          path: app/build/reports/lint
          destination: lint-reports

# Define the workflow to orchestrate jobs.
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
