version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:17-jdk
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install Gradle 8.6
          command: |
            wget https://services.gradle.org/distributions/gradle-8.6-bin.zip
            unzip gradle-8.6-bin.zip
            sudo mv gradle-8.6 /opt/gradle
            sudo ln -s /opt/gradle/bin/gradle /usr/bin/gradle
      - run:
          name: Gradle Build
          command: gradle build
      - run:
          name: Gradle Test
          command: gradle test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
