version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:17-jdk-slim
    steps:
      - checkout
      - run:
          name: Verify Java Version
          command: |
            java -version
            javac -version
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
            unzip gradle-7.6-bin.zip
            sudo mv gradle-7.6 /usr/local/gradle
            sudo ln -s /usr/local/gradle/bin/gradle /usr/bin/gradle
            gradle -v
      - run:
          name: Build
          command: ./gradlew build
      - run:
          name: Test
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
