version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Atau image Docker lain yang sesuai
    steps:
      - checkout
      - run:
          name: Update Package List and Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-17-jdk wget unzip
      - run:
          name: Install Android SDK
          command: |
            mkdir -p $HOME/android-sdk/cmdline-tools/latest
            wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
            unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools/latest
            yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
            $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30"  # Atur versi platform sesuai kebutuhan proyek
      - run:
          name: Set Environment Variables
          command: |
            echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $BASH_ENV
            echo "export ANDROID_HOME=$HOME/android-sdk" >> $BASH_ENV
            echo "export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Make Gradlew Executable
          command: chmod +x ./gradlew
      - run:
          name: Create local.properties
          command: echo "sdk.dir=$ANDROID_HOME" > local.properties
      - run:
          name: Build Project
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
