version: 2.1

orbs:
  android: circleci/android@0.2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-34-alpha
    working_directory: ~/project

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Install Java 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
            sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac 1
            sudo update-alternatives --config java
            sudo update-alternatives --config javac
            java -version
      - run:
          name: Set JAVA_HOME
          command: echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $BASH_ENV
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - restore_cache:
          key: android-orb-v1-{{ checksum "app/build.gradle" }}-{{ checksum "settings.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies --no-daemon
      - save_cache:
          key: android-orb-v1-{{ checksum "app/build.gradle" }}-{{ checksum "settings.gradle" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew assembleDebug --no-daemon
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test --no-daemon
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
